export const routes = {
  home: "/",
  cart: "/cart",
  orders: "/orders",
  checkout: "/orders/checkout",
  tickets: "/tickets",
  login: "/auth/login",
  register: "/auth/register",
  merchant: "/merchant",
  merchantApply: "/merchant/apply",
  merchantProducts: "/merchant/products",
  merchantOrders: "/merchant/orders",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminMerchants: "/admin/merchants",
  adminProducts: "/admin/products",
  adminOrders: "/admin/orders",
  adminTickets: "/admin/tickets",
  customerService: "/cs",
  product: (id: number | string) => `/products/${id}`,
  payOrder: (id: number | string) => `/orders/${id}/pay`,
} as const
